import { NextRequest, NextResponse } from "next/server";
import { supabase } from "../../../../lib/supabaseClient";
import nodemailer from "nodemailer";

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();
    const { firstName, lastName, email, phone, subject, message } = data;

    // ✅ Insert into Supabase
    const { error } = await supabase.from("contact_messages").insert([
      {
        first_name: firstName,
        last_name: lastName,
        email,
        phone,
        subject,
        message,
      },
    ]);

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    // ✅ Setup Nodemailer
    const transporter = nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 465,
      secure: true,
      auth: {
        user: process.env.ADMIN_EMAIL,
        pass: process.env.ADMIN_EMAIL_PASSWORD,
      },
    });

    // ✅ Admin notification email
    const adminMail = {
      from: `WealthFino <${process.env.EMAIL_FROM}>`,
      to: process.env.ADMIN_EMAIL, // send to you
      subject: `📩 New Contact Form Submission - ${firstName} ${lastName}`,
      html: `
        <h2>New Contact Form Submission</h2>
        <p><b>Name:</b> ${firstName} ${lastName}</p>
        <p><b>Email:</b> ${email}</p>
        <p><b>Phone:</b> ${phone}</p>
        <p><b>Subject:</b> ${subject}</p>
        <p><b>Message:</b></p>
        <p>${message}</p>
        <hr/>
        <small>This message was automatically generated by WealthFino website.</small>
      `,
    };

    await transporter.sendMail(adminMail);

    // ✅ Optional: Confirmation email to user
    // Uncomment if you want to send a reply back to the user
    /*
    const userMail = {
      from: `WealthFino <${process.env.EMAIL_FROM}>`,
      to: email,
      subject: "We received your message ✅",
      html: `
        <p>Hi ${firstName},</p>
        <p>Thank you for reaching out to us. Our team has received your message and will get back to you shortly.</p>
        <p>Best regards,<br/>Team WealthFino</p>
      `,
    };
    await transporter.sendMail(userMail);
    */

    return NextResponse.json(
      { message: "Message saved and email sent successfully." },
      { status: 200 }
    );
  } catch (err: any) {
    console.error("Email sending error:", err);
    return NextResponse.json(
      { error: "Failed to process contact form." },
      { status: 500 }
    );
  }
}
